"""add last_message fields to thread

Revision ID: 5da87cd0b832
Revises: b6ec7a256e4b
Create Date: 2026-01-13 17:30:54.763717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5da87cd0b832'
down_revision: Union[str, Sequence[str], None] = 'b6ec7a256e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('threads', sa.Column('last_message_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_threads_last_message_at'), 'threads', ['last_message_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_last_message_at'), table_name='threads')
    op.drop_column('threads', 'last_message_preview')
    op.drop_column('threads', 'last_message_at')
    # ### end Alembic commands ###
